#!/bin/bash

RUN_DIR_PATH=$PWD
LOCATE=$(cat plugins.conf)


USAGE="`basename $0` [-w|--warning]<qsize> [-c|--critical]<qsize>"
THRESHOLD_USAGE="WARNING threshold must be smaller than CRITICAL: `basename $0` $*"

critical=""
warning=""
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
# print usage
if [[ $# -lt 4 ]]
then
        echo ""
        echo "Wrong Syntax: `basename $0` $*"
        echo ""
        echo "Usage: $USAGE"
        echo ""
        exit 0
fi
# read input
while [[ $# -gt 0 ]]
  do
        case "$1" in
               -w|--warning)
               shift
               warning=$1
        ;;
               -c|--critical)
               shift
               critical=$1
        ;;
        esac
        shift
  done
# verify input
if [[ $warning -eq $critical || $critical -lt $warning ]]
then
        echo ""
        echo "$THRESHOLD_USAGE"
        echo ""
        echo "Usage: $USAGE"
        echo ""
        exit 0
fi


#There are totally [8] workers and queue size is [0]
QSIZE=`cd $EVAM_CONSOLE_PATH && $EVAM_CONSOLE_PATH/evam queueStatus $ENGINE_ID | tail -1 | cut -d[ -f3 | cut -d] -f1`
if [[ "$QSIZE" = "" || -z "$QSIZE" ]]
        then
                echo "WARNING: No queue found."
                exit 1
fi

if [[ "$QSIZE" -gt  $critical ]]
        then
                echo "CRITICAL: Biggest Qsize is $QSIZE|qsize=$QSIZE;$warning;$critical;0;0"
                exit 2
fi
if [[ "$QSIZE" -ge  $warning ]]
        then
                echo "WARNING: Biggest Qsize is $QSIZE|qsize=$QSIZE;$warning;$critical;0;0"
                exit 1
fi
if [[ "$QSIZE" -lt  $warning ]]
        then
                echo "OK: Biggest Qsize is $QSIZE|qsize=$QSIZE;$warning;$critical;0;0"
                exit 0
fi
