#!/bin/bash

RUN_DIR_PATH=$PWD
LOCATE=$(cat plugins.conf)


USAGE="`basename $0` [-w|--warning]<qsize> [-c|--critical]<qsize>"
THRESHOLD_USAGE="WARNING threshold must be smaller than CRITICAL: `basename $0` $*"

critical=""
warning=""
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
# print usage
if [[ $# -lt 4 ]]
then
        echo ""
        echo "Wrong Syntax: `basename $0` $*"
        echo ""
        echo "Usage: $USAGE"
        echo ""
        exit 0
fi
# read input
while [[ $# -gt 0 ]]
  do
        case "$1" in
               -w|--warning)
               shift
               warning=$1
        ;;
               -c|--critical)
               shift
               critical=$1
        ;;
        esac
        shift
  done
# verify input
if [[ $warning -eq $critical || $critical -lt $warning ]]
then
        echo ""
        echo "$THRESHOLD_USAGE"
        echo ""
        echo "Usage: $USAGE"
        echo ""
        exit 0
fi


#There are totally [8] workers and queue size is [0]
CURRENT_DATE=`date '+%d/%b/%Y %H'`
RECOVERED_WORKER_TEMP=`cd $EVAM_CONSOLE_PATH && $EVAM_CONSOLE_PATH/evam threadStatus $ENGINE_ID $CURRENT_DATE | wc -l`
RECOVERED_WORKER=`expr $RECOVERED_WORKER_TEMP - 2`


if [[ "$RECOVERED_WORKER" -gt  $critical ]]
        then
                echo "CRITICAL: Recovered worker count is $RECOVERED_WORKER"
                exit 2
fi
if [[ "$RECOVERED_WORKER" -ge  $warning ]]
        then
                echo "WARNING: Recovered worker count is $RECOVERED_WORKER"
                exit 1
fi
if [[ "$RECOVERED_WORKER" -lt  $warning ]]
        then
                echo "OK: Recovered worker count is $RECOVERED_WORKER"
                exit 0
fi
