#!/bin/bash

ENGINE_ID="0"
RUN_DIR_PATH=$PWD
source /etc/evam.conf

USAGE="`basename $0` [-c|--critical]<qsize> [-h|--help]<help>"

critical=""
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3


PROGNAME=`basename $0`

print_help(){
        echo "$PROGNAME is a Nagios Plugin to check working listener process"
        echo "See below for available options."
        echo "Options:"
        echo "  -c/--critical)"
        echo "          Defines critical threshold of listener process"

}





# print usage
if [[ $# -lt 2 && $1 -ne "-h" ]]
then
        echo ""
        echo "Wrong Syntax: `basename $0` $*"
        echo ""
        echo "Usage: $USAGE"
        echo ""
        exit 0
fi
# read input
while [[ $# -gt 0 ]]
  do
        case "$1" in
	       -h|--help)
	       print_help
	       exit 3
	;;
               -c|--critical)
               shift
               critical=$1
        ;;
        esac
        shift
  done

AGENT_COUNT=`ps aux | grep "$EVAM_LISTENER_MAIN_CLASS" | wc -l`

if [[ "$AGENT_COUNT" -lt  $critical ]]
	then
		echo "CRITICAL:  Agent process count is $AGENT_COUNT"
		exit 2
fi
if [[ "$AGENT_COUNT" -gt  $critical ]]
	then
		echo "WARNING:  Agent process count is $AGENT_COUNT"
		exit 1
fi
if [[ "$AGENT_COUNT" -eq  $critical ]]
	then
		echo "OK: Agent process count is $AGENT_COUNT"
		exit 0
fi
						
