#!/bin/bash

RUN_DIR_PATH=$PWD
source /etc/evam.conf

USAGE="`basename $0` [-w|--warning]<qsize> [-c|--critical]<qsize> [-h|--help]<help>"
THRESHOLD_USAGE="WARNING threshold must be smaller than CRITICAL: `basename $0` $*"

critical=""
warning=""
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3

PROGNAME=`basename $0`

print_help(){
        echo "$PROGNAME is a Nagios Plugin to check engine  queue sizes"
        echo "See below for available options."
        echo "Options:"
        echo "  -w/--warning)"
        echo "          Defines warning threshold of queue size"
        echo "  -c/--critical)"
        echo "          Defines critical threshold of queue size"

}



# print usage
if [[ $# -lt 2 && $1 -ne "-h" ]]
then
        echo ""
        echo "Wrong Syntax: `basename $0` $*"
        echo ""
        echo "Usage: $USAGE"
        echo ""
        exit 0
fi
# read input
while [[ $# -gt 0 ]]
  do
        case "$1" in
	       -h|--help)
		print_help
		exit 3
	;;
               -w|--warning)
               shift
               warning=$1
        ;;
               -c|--critical)
               shift
               critical=$1
        ;;
        esac
        shift
  done
# verify input
if [[ $warning -eq $critical || $critical -lt $warning ]]
then
        echo ""
        echo "$THRESHOLD_USAGE"
        echo ""
        echo "Usage: $USAGE"
        echo ""
        exit 0
fi


#There are totally [8] workers and queue size is [0]
QSIZE=`cd $EVAM_CONSOLE_PATH && $EVAM_CONSOLE_PATH/evam queueStatus $ENGINE_ID | tail -1 | cut -d[ -f3 | cut -d] -f1`
if [[ "$QSIZE" = "" || -z "$QSIZE" ]]
        then
                echo "WARNING: No queue found."
                exit 1
fi

if [[ "$QSIZE" -gt  $critical ]]
        then
                echo "CRITICAL: Biggest Qsize is $QSIZE|qsize=$QSIZE;$warning;$critical;0;0"
                exit 2
fi
if [[ "$QSIZE" -ge  $warning ]]
        then
                echo "WARNING: Biggest Qsize is $QSIZE|qsize=$QSIZE;$warning;$critical;0;0"
                exit 1
fi
if [[ "$QSIZE" -lt  $warning ]]
        then
                echo "OK: Biggest Qsize is $QSIZE|qsize=$QSIZE;$warning;$critical;0;0"
                exit 0
fi
